pipeline{
    agent any
    tools{
      maven 'M2_HOME'
    }
    stages{
      stage('sonarscan'){
        steps{
            sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Mmuashan_geo-app'
        }
      }   
     stage("maven"){
        steps{
        sh 'mvn clean validate compile install test package'
        }  
     } 
     stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP9qGsugWCiUaaBCRDWmsd7tZbU -T \
            target/bio*.jar \
            "http://ec2-100-26-175-21.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
        }
      }
    }
}